---
collections:
  # AWX uses a very old version of ansible-core
  - name: ansible.netcommon
    version: "5.3.0"
  - name: ansible.utils
    version: "4.1.0"
  - name: check_point.gaia
    version: "7.0.0"
