---
- name: Includes and Imports Ex1 (part a)
  hosts: localhost
  tasks:
    - name: Loops and include
      ansible.builtin.include_tasks: subtask1.yml
      loop:
        - 10.1.1.1
        - 10.1.1.2
        - 10.1.1.3
        - 10.1.1.4
