---
- hosts: mgmt
  gather_facts: false
  tasks:
    - name: show-access-rulebase
      check_point.mgmt.cp_mgmt_access_rule_facts:
        name: Network
        details_level: standard
        use_object_dictionary: true
        limit: 20
        offset: 0
      register: policy

    - name: Objects Dictionary
      ansible.builtin.set_fact:
        objects_list: "{{ policy.ansible_facts['access-rulebase']['objects-dictionary'] }}"

    - name: Rulebase
      ansible.builtin.set_fact:
        rulebase: "{{ policy.ansible_facts['access-rulebase'].rulebase }}"

    - debug:
        var: objects_list

    - name: Simplify Objection Dictionary
      ansible.builtin.set_fact:
        uids: "{{ objects_list | map(attribute='uid') | list }}"
        names: "{{ objects_list | map(attribute='name') | list }}"

    - name: Unify names and uids
      ansible.builtin.set_fact:
        object_names_uids: "{{ names | zip(uids) | list }}"

    - debug:
        var: object_names_uids
 
#    - debug:
#        var: rulebase
#        var: objects_list
